language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: d3IRhxZYHkOHkAERn/1KCiHgybrlJH3QI5zTafxqMXa/jQ4eVjCEk/3GHDP97QhjG4wDD/+0DzrKvxxXWS8HJFKMGjhq82qhkQSxBQvaR1D184ZNdlCntT3R4B4YjRQJQV4zJjj2DeGHrgoUNaODUGOzsaollmWKqbe19ULaURga3eEaIxM/QWwowcWsJXQMLdgxUC/AkPlwmjZrezGc/3jZreWtCxg98JzkN4zrMzFsIUINB8ABteBlyc+dpclGkjW8gSOFi/2b56lMk//es24ldjhQ1wSNprSx8aTNgkYC3Pd6ZZsjFSRzTWaKIZOyKOv92ZCN99ORWd9AymkhE1tXAFO1Or47KmrKOddx7sMCHRZYcL06oknk+NC7qSpYFxOFGxdjW363WWni2RMHR1XhfRRBlU3pc5eBTiq1s8idbuNvxs28QEKe6VzyM6UB6/ce89qEzlC2ZCJ9PKBYZW8HtzTUZ2SZBMCQ8Y6tGqpYJGuVK+VyB50Y8gjQxvjXbJmnsL7thauY6+faBRq6MYnfsVW4lT+/xMb7gFlbDinaPc5kGx29YM4fU2UX8qQKPfQKAN+0M7hlNRHSHPj7dfyWJ7it9hLJVJ11wUaIR/hIHeJa+nFKJ8GtoV2H70zZki89VobtI25RABEetDdJYVfLKvyCrD8HNX4c7iHQIXE=
  app: lit-journey-4733
  on:
    repo: KahokuHanten/oyako
  run:
  - rake db:migrate
  - rake db:seed
cache:
  directories:
  - vendor/bundle
addons:
  postgresql: '9.3'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
notifications:
  slack:
    secure: rgIOezoWFKVy6FE0wPUX4g/eapyoEb3OfVJCYrhvcfjX5WqEuIFaomYEk7rOiqRP8uy0YIXsQWswBgaiiAKhTZBN779ztGDjAX8f+ikior37XKPhq8CPGALtmVmeIIzf61UlrEzVKEFGkIRoWg02iieazij73074qaJbjlppbnjs54cgYFovcZM9sd3mfzvpJpEp0zkZGgc7ULlgHTOp2kDlo54J2lhFaf7pXoClk2ujgYbtMJ1ozcktE/gl3jDWLXoUlvRpHVvMnye71x8dqSP9NcY6HZ9kywyT0FleWNFAZJHGhZj9ffv2rtKMX09JP45chQBiteF9F3150eZu7N5tWxxrAqQam6e9zxNczoD9TB7hQvYNfXlC6Bg1wS8QqL+BMzRPqN+lRHZrzdXJTGIdaybEKwyUIG/V0GbLEIDqMx6JewY4haY55/w0bECU1Pjv4fdG4ke8DiNDX4JnMlLKBj92a4uJKV9YAVdH/887ox98N6G7kHQwpT0Njf/9/Haib2F62IAuY0RSTmGobfEz68+XqoxdVBx/kOvUSmZr5HLONbLrrd/fwljHYzTSYYrqBIn4Lh246ljg6F8OfzR8ik24LrU45S6I68Aylet87uZ2VRtw4PTkoNjs+J6rzBkhRcl+gD3DAONIJEQxc0mcjTKyJK7ldVsPyqTuWso=
env:
  global:
  - secure: EtkldNKTa/9WReCBn9czmvHLvf4THSOCVVac1TGf8U1aXYr3LWoelnCwG2gXysP56I5AL4rfQP6LKf/Mo1Wij+MWzIQuLAiQy1lnq8js0sB6piqqM6LlGPJ6Ifhd09FZhEbfxMQWopyc0VJbzCDQ8DU5Cl05NX82Z+3q1b/6Ik0XALUh2q5NphgUL4dZIc7DccUElZeu24JCJ9VMO2OE+Jt5swqiemxN7K0qiQ1ckXzGmSBjKWagzpaHfLA+gJkVNNFuBZ3EXi5vP75BXuyCjh4j+SIM6wIWn4eOgHBqOFOW6vFsiBQ9DAhc2kbciaKSIGHQyp0xqOr4IScqSUoTVvEWCGoR0KmSoJJakjV9+3KcFz/k07xn1U+McIm8wZoWH1It+06du5Njux8Him2/Cft8/BUFNYHHBYQC43Oe32Ff29lsk/7dr3QhL2XgxLx7TO42cwcYnBD1pICPz8YT4DDq1aesVN1SVBPj/JYBoKzrdhQzpYy9hnEN8rNbjCRBndZzq3AfJiBlokygVpASgvGLbBFXgrEfuWtyph4JTQBjwZeYd/lYAJTbTZqqtwWxIR0EqYaIZZGfImRdPIM0zvWNffhER2SVCn6UZLKeAjLhpRJ6bm92NBqfOA5R0ffIf8WTFtgY40ZLAY8IzxCSuhJnTGjVnS8LRY6zIAIFEQM=
  - secure: uaZeBqhVqL1atC5q0qW3CDUP93R0/PPi+vbeeVG1UHhVOmnNkz/jtS/pfwlgoFgepV/2e9AwPBmN9Tnp6RkpPREGes2iGe802wgYWfriLNMvSsW6Fw9M8HqjYuodgrp5tRTwQ+5o94KrjZc/tU20EBo322Ac4rZtqZ0TgLxgZ1jgS82qMNpmMjdNg5EAYqS9hmC8yL2xl7t62Xl67eAmVa3NBVsbUvv9XJ2uFgBYExwdnLqAsaieUCAVDeEWx8i3JS0vtla1cLbaJhLbSvLFiho9QGcDv3kq0woJJ4FoR4QtytuNeWc8Foy4DAta+4Nrnp3nkk/RmFn8z1tT/L3KyNfO76YOEb7oqgahcMZwkQDHuFVUTMAljkdOcIVRBOqsElI9ECObBFqWJjTXxhlxq+/6vSdGb1wOZYX6Z0ydIqaFwyvnZ49uXjWra6Vqnqpx/hlz99Cl0/RPHRrkMvb9YLaN7QaTyo5cXbzkNx+cIYY4D3BZT9OmJFNKMYSCSMkkw8dJjHHDlx1DbQ41FZkTvC4q+S4ql63nTGf8FVrhDHsFDfQRdckhYgvF3a+ms8P5rNpEyHDorSdoHKjR1a3vQ3dd1ezi8d+DuoAY1xlfGjv7D7H4MvNtZh4wS0X/VzOfZ+bqYNxs1JE2RBmNzsrFUbEwQWqy3H7nauFtLCU6vb0=
